[main]
num_threads = 12
dt_pde = 0.020000
simulation_time = 1500.000000
abort_on_no_activity = 1
use_adaptivity = 0

[ode_solver]
dt = 0.020000
use_gpu = 1
gpu_id = 0
library_file = shared_libs/libten_tusscher_tt3_mixed_endo_mid_epi.so

[stimulus]
main_function = set_stim_from_file
library_file = ./shared_libs/libdefault_stimuli.so
start = 0
duration = 2.0
current = -38.0
stim_file = local_stims/Patient_1_endocardium_points.pts

[domain]
main_function = initialize_grid_with_hu_mesh_with_scar
library_file = ./shared_libs/libdefault_domains.so
name = HU Mesh 3D
original_discretization = 500.0
desired_discretization = 500.0
num_volumes = 2058822
mesh_file = meshes/Patient_1.alg
num_extra_fields = 11
start_dx = 500.000000
start_dy = 500.000000
start_dz = 500.000000

[assembly_matrix]
init_function=set_initial_conditions_fvm
sigma_x = 0.000313
sigma_y = 0.000313 / 10
sigma_z = 0.000313 / 10  
main_function=homogeneous_sigma_assembly_matrix

[update_monodomain]
main_function = update_monodomain_default
library_file = ./shared_libs/libdefault_update_monodomain.so

[linear_system_solver]
main_function = conjugate_gradient
init_function = init_conjugate_gradient
end_function = end_conjugate_gradient
tolerance = 1e-9
use_preconditioner = no
use_gpu = yes
max_iterations = 200

[extra_data]
main_function=set_extra_data_mixed_tt3_endo
;main_function = set_extra_data_mixed_tt3_from_file

[save_result]
main_function = save_ecg_data
init_function = init_save_ecg_data
end_function = end_save_ecg_data
library_file = ./shared_libs/libdefault_save_mesh.so
print_rate = 100
output_dir = ./outputs/TCC_matheus/P1
binary = true
mesh_format = ensight
mesh_print_rate = 100
file_prefix = V
abort_on_no_activity = true
last_stimulus_time = 5112.0
vm_threshold = -86.0
remove_older_simulation = true

;[save_state]
;main_function = save_simulation_state_with_activation_times
;input_dir = ./outputs/P1_estimulo_Endo/

[calc_ecg]
main_function = pseudo_bidomain
init_function = init_pseudo_bidomain
end_function = end_pseudo_bidomain
calc_rate = 10
lead1 = 0,0,0
sigma_b = 20
use_gpu = true
;filename = ./outputs/P1_new_Endo_ecg/ecg.txt

;LEADS_AUTOMATICO = np.array(
;    [
;    [-54753.203738,  62456.124804, -6759.670047],  # V1
;    [-40212.963090,  35810.565855,  17365.300468],  # V2
;    [-23313.249073,  22062.935218,  43743.364971],  # V3
;    [-4762.928479,  12965.251729,  68967.960256],  # V4
;    [ 53196.544270, -49193.916471,  73974.301329],  # V5
;    [ 114166.439868, -83256.599535,  46330.855771],  # V6
;    ],
;    dtype=np.float64,
;)

;LEADS_Manual = np.array(
;    [
;    [-50586.634041,  64134.374649, -499.676268],  # V1
;    [-37258.057459,  27176.130632,  21947.302270],  # V2
;    [-18730.933644,  13671.968481,  49109.919738],  # V3
;    [ 3621.969181,  2844.584974,  71788.122967],  # V4
;    [ 110868.014494, -75368.245503,  56223.444568],  # V5
;    [ 142960.777382, -86848.830064,  35965.622663],  # V6
;    ],
;    dtype=np.float64,
;)
